name: Build OnvifDeviceManager deb package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image and deb package
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: onvif-device-manager:latest
        outputs: type=docker,dest=/tmp/onvif-device-manager.tar

    - name: Load Docker image
      run: docker load --input /tmp/onvif-device-manager.tar

    - name: Copy deb package from Docker container
      run: |
        container_id=$(docker create onvif-device-manager:latest)
        docker cp $container_id:/*.deb ./
        docker rm $container_id

    - name: Upload deb package
      uses: actions/upload-artifact@v3
      with:
        name: onvif-device-manager-deb
        path: ./*.deb
